# Ref to enum rmw_qos_history_policy_t
int8 history

# Ref to size_t depth
int64 depth

# Ref to enum rmw_qos_reliability_policy_t
int8 reliability

# Ref to enum rmw_qos_durability_policy_t
int8 durability

# Ref to struct rmw_time_t deadline
float64 deadline_ms

# Ref to struct rmw_time_t lifespan
float64 lifespan_ms

# Ref to enum rmw_qos_liveliness_policy_t
int8 liveliness

# Ref to struct rmw_time_t liveliness_lease_duration
float64 liveliness_lease_duration_ms