# Data server control signal
DataServerStatus request

---
# response true if value accepted, otherwise server ignore the request and response false.
bool response

# If <response> response flase, describes the reason.
string reason

# Response current data server status.
DataServerStatus status