# Set node interaction.

# Request device id.
string device_id

# Interactive node signals.
InteractiveNode interactive_node

# The function name could be variant for different nodes, and user should define the function name for each node.
string node_command_name

# The arguments could be variant for different nodes, and user should define the arguments for each node.
string[] node_command_args

---
# response is true if value accepted, otherwise server ignore the request and response false.
## Returns true if request success. Otherwise, returns false if:
## 1. Node is not interactable.
## 2. The <device_id> does not have the privilege.
## 3. The <node_command_name> not implemented.
bool response

# If <response> response flase, describes the reason.
string reason