# Get topic_name QoS setting
string topic_name

## Set to 'publisher', 'subscription'
string qos_type

---
# response is true if value accepted, otherwise server ignore the request and response false
bool response

# If <response> response flase, describes the reason.
string reason

# Unique ID describes current qos profile
uint64 qid

# QoS Profile Setting
QosProfile qos_profile
