# Get topic_name QoS setting
string topic_name

## Set to 'publisher', 'subscription' or 'both'
string qos_type "both"

---
# response is true if value accepted, otherwise server ignore the request and response false
bool response

# If <response> response flase, describes the reason.
string reason

# Unique ID describes current qos profile
uint64 qid

# topic names
string[] topic_name_vec

# QoS types
string[] qos_type_vec

# QoS Profile Setting
QosProfile[] qos_profile_vec
